### ISSUE TITLE
Breaking setup of different objects

### ISSUE THREAD

**Issue by immangat** [COMP2522/project-dungeon-quad#107]
More methods can be made that handle setup for one thing only.
eg. setupEnimes();
      setupPlayer(); etc.

https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L73

**Comment by BardiaTiM** [comment]
We cleaned this part up, but chose not to go with objects as it would add more lines and bloating to window.
