### ISSUE TITLE
Too many if statements

### ISSUE THREAD

**Issue by immangat** [COMP2522/project-dungeon-quad#111]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L256

Breaking if statements into separate methods that are called. 

Maybe have all frames that already set up inside the player as PImage[] so you don't have to load it everytime.

**Comment by BardiaTiM** [comment]
Broken down.
