### ISSUE TITLE
Refactor ConcurrentLinkedQueues

### ISSUE THREAD

**Issue by jamesnll** [COMP2522/project-dungeon-quad#120]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Bullet.java#L27-L29

call these queues from window or delete the window queues

**Comment by BardiaTiM** [comment]
Fixed, thanks for great feedback.
