### ISSUE TITLE
Making a drawable interface

### ISSUE THREAD

**Issue by immangat** [COMP2522/project-dungeon-quad#130]
Maybe implement drawable on all enemies  and use a drawable array to iterate to draw them instead of having them in different loops.

https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L208

**Comment by BardiaTiM** [comment]
draw methods are specific, the design pattern is fixed for that.
