### ISSUE TITLE
At end of game, new leaderboard entry doesn't show in menu

### ISSUE THREAD

**Issue by MatoCode** [COMP2522/project-dungeon-quad#131]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/FirebaseLeaderboard.java#L20

After entering a new leaderboard entry at the games end, the leaderboard is not updated

**Comment by BardiaTiM** [comment]
Must be in top ten. Thanks.
