### ISSUE TITLE
Add a little more detail in method comments

### ISSUE THREAD

**Issue by MatoCode** [COMP2522/project-dungeon-quad#132]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Skeleton.java#L124

with having 2 overloaded draw methods, you should add some detail about what each parameter is so it is easier to tell what each function does differently

**Comment by BardiaTiM** [comment]
Completed with more detail. Thanks
