### ISSUE TITLE
Magic Numbers

### ISSUE THREAD

**Issue by MikeSusutZZ** [COMP2522/project-dungeon-quad#137]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L87

Magic numbers, if these are starting positions could be based on window size instead of scalability

**Comment by BardiaTiM** [comment]
Chosen exact location because window size might be changed as a setting.
