### ISSUE TITLE
Make these into an Enemies Interface

### ISSUE THREAD

**Issue by MikeSusutZZ** [COMP2522/project-dungeon-quad#145]
If you make all enemies be under an interface you can call all of them at once instead of doing

https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L208

**Comment by BardiaTiM** [comment]
Closed without fix, unable to implement this in time.
