### ISSUE TITLE
vague variable name

### ISSUE THREAD

**Issue by LaurieSolkoski** [COMP2522/project-dungeon-quad#151]
could name the variable to something more descriptive other than just vy or vx (even though it already describes the variable in the java docs)
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Boulder.java#L33

**Comment by BardiaTiM** [comment]
Completed. Thanks.
