### ISSUE TITLE
Difficult to understand the purpose of scheduler here. 

### ISSUE THREAD

**Issue by michelle-0** [COMP2522/project-dungeon-quad#154]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Skeleton.java#L65

scheduler could use more javadoc to explain its purpose, and help the reader understand what scheduler is doing in this line.

**Comment by BardiaTiM** [comment]
Added some more detail. Thank you :)
