### ISSUE TITLE
The name of files can be defined as variables to make code cleaner.

### ISSUE THREAD

**Issue by michelle-0** [COMP2522/project-dungeon-quad#157]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L261

So instead of putting full file path in the code, can define it at the top as a variable first.

**Comment by BardiaTiM** [comment]
Fixed.
