### ISSUE TITLE
Javadoc references Player, but the code references Sprite.

### ISSUE THREAD

**Issue by michelle-0** [COMP2522/project-dungeon-quad#161]
https://github.com/COMP2522/project-dungeon-quad/blob/b90ff2e227e75ad54604e243b73f975613bddc06/src/main/java/org/bcit/comp2522/project/Window.java#L254

Naming of player and sprite can be more consistent. Can just choose one, rather than reference Player in method javadoc but have the code call on Sprite.

**Comment by BardiaTiM** [comment]
We changed all "Sprite" usage to "Player" issue fixed. Thanks.
