### ISSUE TITLE
potential primitive obsession

### ISSUE THREAD

**Issue by LaurieSolkoski** [COMP2522/project-dungeon-quad#177]
source from refractoring guru

the key has primitive type char, could consider using an enum to represent the values

https://github.com/COMP2522/project-dungeon-quad/blob/ebfd55a80a8c9e71b80b2a2af8bb44fd5e6c1315/src/main/java/org/bcit/comp2522/project/SpawningHandler.java#L33

**Comment by BardiaTiM** [comment]
We ended up choosing to go a separate path from this, thank you.
