### ISSUE TITLE
spawning logic redundancy

### ISSUE THREAD

**Issue by LaurieSolkoski** [COMP2522/project-dungeon-quad#178]
the spawning for skeletons, goblins, and trolls are kind of the same/have the same idea. I'm not exactly sure how but I think the logic in those methods could be combined into one method?

https://github.com/COMP2522/project-dungeon-quad/blob/ebfd55a80a8c9e71b80b2a2af8bb44fd5e6c1315/src/main/java/org/bcit/comp2522/project/SpawningHandler.java#L44

**Comment by BardiaTiM** [comment]
They have different draw methods, movement, update, attacking. Not sure how they can be combined.
