### ISSUE TITLE
Really long method

### ISSUE THREAD

**Issue by LaurieSolkoski** [COMP2522/project-dungeon-quad#179]
Could consider breaking down the individual methods into smaller methods. handleMonsterSpawning() is really long

https://github.com/COMP2522/project-dungeon-quad/blob/ebfd55a80a8c9e71b80b2a2af8bb44fd5e6c1315/src/main/java/org/bcit/comp2522/project/SpawningHandler.java#L33

**Comment by BardiaTiM** [comment]
Fixed.
