### ISSUE TITLE
Refactor buttons to be in Menu Class

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-dungeon-quad#67]
Duplicate variables can be removed and only instantiated in Menu.

https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Window.java#L60

https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Menu.java#L41

https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Menu.java#L50

**Comment by pbucci** [comment]
Tried deleting from Window.java and only one error popped up -> removable

**Comment by BardiaTiM** [comment]
Completed
