### ISSUE TITLE
Magic numbers and repeated constants can be refactored into parameter

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-dungeon-quad#68]
https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Menu.java#L50

**Comment by pbucci** [comment]
`width = window.getwidth() / 2 - 100` e.g.

**Comment by pbucci** [comment]
https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Menu.java#L53

This line is the only one that has a different w/2 - 100 pattern, can we put this relative to the above width variable?

**Comment by pbucci** [comment]
Suggest creating a offset system rather than a absolute positioning system

**Comment by BardiaTiM** [comment]
Completed
