### ISSUE TITLE
2 repeat booleans, alive, IsAlive

### ISSUE THREAD

**Issue by MikeSusutZZ** [COMP2522/project-dungeon-quad#74]
https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Goblin.java#L37

Seems to be 2 booleans for whether or not the creature is alive

**Comment by gathrean** [comment]
Completed.
