### ISSUE TITLE
looks like these images are not being used

### ISSUE THREAD

**Issue by shawnbirring** [COMP2522/project-dungeon-quad#77]
consider removing these variables since they are not doing anything. also when removed it does not cause any errors

https://github.com/COMP2522/project-dungeon-quad/blob/17b9ee6d1a264dc8e8dc527aafb3c04da33b48f1/src/main/java/org/bcit/comp2522/project/Window.java#LL41-L43C21

**Comment by gathrean** [comment]
Completed.
